version: 2
jobs:
  build:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          # -vNUM is a version toggle for busting cache
          key: node_modules_{{ checksum "package.json" }}-v0
      - run:
          name: Install node modules
          command: npm i
      - save_cache:
          # Must mach number above
          key: node_modules_{{ checksum "package.json" }}-v0
          paths:
          - ~/ionic/node_modules/

      - run:
          name: Checksum scripts
          command: npm run checksum

  framework:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: api_{{ checksum ".tmp/api.txt" }}-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Framework Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen framework
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: api_{{ checksum ".tmp/api.txt" }}-v0
          paths:
            - sources/ionic/

  cli:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: cli_{{ checksum ".tmp/cli.txt" }}-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate CLI Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen cli
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: cli_{{ checksum ".tmp/cli.txt" }}-v0
          paths:
            - sources/ionic-cli/

  component-preview:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: component-preview_{{ checksum ".tmp/cli.txt" }}-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen component
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: component-preview_{{ checksum ".tmp/cli.txt" }}-v0
          paths:
            - sources/component-preview/

  native:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: native_{{ checksum ".tmp/cli.txt" }}-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen native
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: native_{{ checksum ".tmp/cli.txt" }}-v0
          paths:
            - sources/ionic-native/

  storage:
    docker:
      - image: node:10
    steps:
      - checkout
      - restore_cache:
          key: storage_{{ checksum ".tmp/cli.txt" }}-v0
      # Generate Docs for each section concurrently
      - run:
          name: Generate Component Preview Docs
          no_output_timeout: 20m
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                npm run docgen storage
              else
                echo "We are on ${CIRCLE_BRANCH} branch, not going to update docs."
              fi
      - save_cache:
          key: storage_{{ checksum ".tmp/cli.txt" }}-v0
          paths:
            - sources/ionic-storage/

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - framework:
          requires:
            - build
      - cli:
          requires:
            - build
      - component-preview:
          requires:
            - build
      - native:
          requires:
            - build
      - storage:
          requires:
            - build