version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    branches:
      only:
        - master

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run build-case
      - deploy:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Deploy"
              npx netlify-cli deploy \
                --site ${DEV_SITE_ID} \
                --dir www/ \
                --auth ${NETLIFY_TOKEN} \
                --prod
            else
              echo "Not master branch so not deploying"
            fi
